project:
  type: website
  output-dir: docs

website:
  title: "Richard Dickson Amoako"
  site-url: https://www.rd-amoako.com
  description: "This is RD Amoako's personal Blog."
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Publications"
        href: publication.qmd
    
    right:
      - icon: github
        href: https://github.com/amoakor
      - icon: linkedin
        href: https://tiny.utk.edu/ramoako
  cookie-consent: true

format:
  html:
    theme: flatly  # Changed from theme.scss, cosmo to built-in theme
    css: styles.css
     
# filters:
#   - code-filename

editor: visual
execute:
  echo: false
  error: true
  warning: true
  include: true
  cache: true
  freeze: true
  message: false
  output: true
  run-chunk-labels: false
  